### PR TITLE
Spiralsearchpattern

### PR DESCRIPTION
**Pull request by Babun3000**
new search pattern "spiral" in search_beacon function, 
new function send_ned_velocity for moving the drone continuously, 
new optional parser for pattern choosing, 
new parameters for search pattern spiral, 
if rpi.gpio is unavailable script is not stopping but signal detection is 
av_im005
inactive

### CODE REVIEW

**Comment by moobsen** [comment]
Nicely done, thank you!

Let me know if you want to test this on a real drone with me.

But I want to be able to choose between search modes (spiral/meander) so not merging into master branch for now.

**Review by moobsen — CHANGES_REQUESTED** [review]
See https://github.com/moobsen/beacon_search/pull/1#issuecomment-736620826

Also please create a feature branch. (https://gist.github.com/vlandham/3b2b79c40bc7353ae95a)

**Comment by Babun3000** [comment]
I did some last changes. I think i created correctly the feature branch "spiralsearchpattern". The commits are in total: 
1. I added a parser --searchpatter the user optionally use to activate a spiral search pattern instead of a meander search pattern. The parser is transferred as a optional argument to the function search_beacon. In search_beacon I forked Step 3 by an if-statement into the two search pattern "meander" and "spiral". As long as it's only these two I thought no additional functions/procedures are needed. 
2. If the platform is not a RPi or the package rpi.gpio is not installed the script will not break, since I added a try and except option. There is only an information in the search.log
3. When calling the init-function boolean signal_detection is now written to the class argument self.signal_detection. Otherwise --nosearch has no effect. 
4. I added some parameters for the spiral search pattern

**Comment by Babun3000** [comment]
And yes! If you found time to check out the code - and it could work on a real drone - then we should definetly have a try and a drink

**Pull request merged**
